### ISSUE TITLE
Django 2.1 support

### ISSUE THREAD

**Issue by rehug** [trentm/django-markdown-deux#31]
I tried django 2.1 today as I saw that view permision's added, but found that error occurs when I tried to add a post. 
`TypeError: render() got an unexpected keyword argument 'renderer'` . 
Further detail as follows
![image](https://user-images.githubusercontent.com/17831097/43673864-72f9e700-97fc-11e8-9b18-6a3b82912767.png)

**Comment by indigodomo** [comment]
What is everyone else doing? I'm making the (huge) jump from Django 1.9/Python 2.7 to Django 2.2/Python 3.7.

**Comment by prateekmadhikar** [comment]
> What is everyone else doing? I'm making the (huge) jump from Django 1.9/Python 2.7 to Django 2.2/Python 3.7.

3 year late ping but what did you do here?

**Comment by indigo-jay** [comment]
Sorry, too long ago, I don't recall.

**Comment by xrmx** [comment]
Pretty sure this is unrelated to this package as we don't have forms here :)
